// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Grapher
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050005
			public const int SampleVideoView = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int button2 = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int graph1 = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int graph2 = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int movieBtn = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int myButton = 2131034114;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int GraphView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int VideoPlayer = 2130903042;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] TelemetryGraph;
			
			private Styleable()
			{
			}
		}
	}
}
